config/routes.rb
Rails.application.routes.draw do
  resources :railway_stations
  resources :trains
  resources :routes
  resources :wagons
  resources :tickets

  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/route.rb
class Route < ActiveRecord::Base
  validates :name, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true

  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :railway_station
  belongs_to :route
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :train
  belongs_to :user
end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  has_many :tickets
  belongs_to :route
  has_many :wagons
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickes
end

app/models/wagon.rb
class Wagon < ApplicationRecord
  belongs_to :train
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: %i[ show edit update destroy ]

  # GET /railway_stations or /railway_stations.json
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1 or /railway_stations/1.json
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations or /railway_stations.json
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to @railway_station, notice: "Railway station was successfully created." }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railway_stations/1 or /railway_stations/1.json
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to @railway_station, notice: "Railway station was successfully updated." }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railway_stations/1 or /railway_stations/1.json
  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: "Railway station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[show edit update destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket #редирект на этот объек (show)
    else
      render :new # отрендерить на new render сохранит объект
    end
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:number)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[show edit update destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to @train
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id)
  end
end

app/controllers/wagons_controller.rb
class WagonsController < ApplicationController
  before_action :set_wagon, only: %i[show edit update destroy]

  def index
    @wagons = Wagon.all
  end

  def show
  end

  def new
    @wagon = Wagon.new
  end

  def create
    @wagon = Wagon.new(wagon_params)

    if @wagon.save
      redirect_to @wagon
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @wagon.update(wagon_params)
      redirect_to @wagon
    else
      render :edit
    end
  end

  def destroy
    @wagon.destroy
    redirect_to wagons_path
  end

  private

  def set_wagon
    @wagon = Wagon.find(params[:id])
  end

  def wagon_params
    params.require(:wagon).permit(:number, :type_wagon, :cnt_top_place, :cnt_bottom_place, :train_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this railway_station from being saved:</h2>

    <ul>
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <footer>
    (с) 2021 Архипов Виталий. Учебный проект в онлайн-школе Thinknetica
    <a href="/">Главная</a>
  </footer>
</html>

app/views/railway_stations/_form.html.erb
<%= form_with(model: railway_station) do |form| %>
  <%= render 'common/errors', resource: @railway_station %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to 'Показать', railway_station %></td>
  <td><%= link_to 'Редактировать', edit_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Удалить', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Назад', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить станцию', new_railway_station_path %>

app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Назад', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>

app/views/routes/_form.html.erb
<%= form_with(model: @route) do |form| %>
  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "#{ route.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/routes/_route.html.erb
<tr>
  <td><%= route.name %></td>
  <td><%= link_to 'Показать', route %></td>
  <td><%= link_to 'Редактировать', edit_route_path(route) %></td>
  <td><%= link_to 'Удалить', route, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/routes/edit.html.erb
<h1>Добавить маршрут</h1>

<%= render 'form', route: @route %>

<%= link_to 'Назад', route_path %><br>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список маршрутов</h1>

<table>
  <thead>
  <tr>
    <th>Имя</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%=render @routes %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить маршрут', new_route_path %>

app/views/routes/new.html.erb
<h1>Добавить маршрут</h1>

<%= render 'form', route: @route %>

<%= link_to 'Назад', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Имя:</strong>
  <%= @route.name %>
</p>
<p>
  <strong>Имя:</strong>
  <%= @route.name %>
</p>
<p>
  <strong>Список поездов на маршруте:</strong>
  <% if @route.trains.present? %>
    <% @route.trains.each do |train| %>
      <%= train.number %> |
    <% end %>
  <% else %>
    Поездов нет
  <% end %>
</p>

<%= link_to 'Редактировать', edit_route_path(@route) %> |
<%= link_to 'Назад', routes_path %>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <%= render 'common/errors', resource: @ticket %>
  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :train, "Поезд" %>
    <%= form.collection_select :train_id, Train.all, :id, :number %>
  </div>

  <div class="field">
    <%= form.label :user, "Пользователь" %>
    <%= form.collection_select :user_id, User.all, :id, :name %>
  </div>


  <div class="actions">
    <%= form.submit "#{ ticket.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<tr>
  <td><%= ticket.number %></td>
  <td><%= link_to 'Показать', ticket %></td>
  <td><%= link_to 'Редактировать', edit_ticket_path(ticket) %></td>
  <td><%= link_to 'Удалить', ticket, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список билетов</h1>

<table>
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @tickets %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить билет', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>Добавить билет</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Назад', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер билета:</strong>
  <%= @ticket.number %>
</p>

<p>
  <strong>Поезд:</strong>
  <%= @ticket.train.number %>
</p>

<p>
  <strong>Пользователь:</strong>
  <%= @ticket.user.name %>
</p>

<%= link_to 'Редактировать', edit_ticket_path(@ticket) %> |
<%= link_to 'Назад', tickets_path %>

app/views/trains/_form.html.erb
<%= form_with(model: train) do |form| %>
<%= render 'common/errors', resource: @train %>
  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :current_station, "Текущая станция" %>
     <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :route, 'Маршрут' %>
     <%= form.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit "#{ train.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Показать', train %></td>
  <td><%= link_to 'Редактировать', edit_train_path(train) %></td>
  <td><%= link_to 'Удалить', train, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Изменить поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Назад', train_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список поездов</h1>

<table>
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить поезд', new_train_path %>

app/views/trains/new.html.erb
<h1>Добавить поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Назад', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер:</strong>
  <%= @train.number %>
</p>
<p>
  <strong>На станции: </strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Не указана
  <% end %>
</p>
<p>
  <strong>Маршрут: </strong>
  <% if @train.route.present? %>
    <%= @train.route.name %>
  <% else %>
    Маршрут не назначен
  <% end %>
</p>
<p>
  <strong>Вагоны прикрепленные к поезду: </strong>
  <% if @train.wagons.present? %>
    <% @train.wagons.each do |wagon| %>
      <%= wagon.number %> |
    <% end %>
    Всего: <%= @train.wagons.count %> wagon
  <% else %>
    У поезда нет вагонов
  <% end %>
</p>

<div>
  <strong>Количество плацкартных вагонов</strong>
  <%= @train.wagons.where(type_wagon: 'Плацкард').count %>

  <p>
    Нижние: <%= @train.wagons.where(type_wagon: 'Плацкард').sum(:cnt_bottom_place) %>
  </p>
  <p>
    Верхние: <%= @train.wagons.where(type_wagon: 'Плацкард').sum(:cnt_top_place) %>
  </p>
</div>

<div>
  <strong>Количество купейных вагонов</strong>
  <%= @train.wagons.where(type_wagon: 'Купе').count %>

  <p>
    Нижние: <%= @train.wagons.where(type_wagon: 'Купе').sum(:cnt_bottom_place) %>
  </p>
  <p>
    Верхние: <%= @train.wagons.where(type_wagon: 'Купе').sum(:cnt_top_place) %>
  </p>
</div>

<%= link_to 'Редактировать', edit_train_path(@train) %> |
<%= link_to 'Назад', trains_path %>

app/views/wagons/_form.html.erb
<%= form_with(model: wagon) do |form| %>
  <%= render 'common/errors', resource: @wagon %>
  <div class="field">
    <%= form.label 'Номер вагона' %>
    <%= form.text_field :number %>
  </div>
  <div class="field">
    <%= form.label 'Тип вагона' %>
    <%= form.select :type_wagon, ['Плацкард', 'Купе'] %>
  </div>
  <div class="field">
    <%= form.label 'Поезд' %>
    <%= form.collection_select :train_id, Train.all, :id, :number %>
  </div>

  <div class="field">
    <%= form.label 'Количество верхних мест' %>
    <%= form.number_field :cnt_top_place %>
  </div>
  <div class="field">
    <%= form.label 'Количество нижних мест' %>
    <%= form.number_field :cnt_bottom_place %>
  </div>

  <div class="actions">
    <%= form.submit "#{ wagon.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/wagons/_wagon.html.erb
<tr>
  <td><%= wagon.number %></td>
  <td><%= link_to 'Показать', wagon %></td>
  <td><%= link_to 'Редактировать', edit_wagon_path(wagon) %></td>
  <td><%= link_to 'Удалить', wagon, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/wagons/edit.html.erb
<h1>Изменить вагон</h1>

<%= render 'form', wagon: @wagon %>

<%= link_to 'Назад', wagon_path %>

app/views/wagons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список вагонов</h1>

<table>
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @wagons %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить вагон', new_wagon_path %>

app/views/wagons/new.html.erb
<h1>Добавить вагон</h1>

<%= render 'form', wagon: @wagon %>

<%= link_to 'Назад', wagons_path %>

app/views/wagons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер:</strong>
  <%= @wagon.number %>
</p>
<p>
  <strong>Тип вагона:</strong>
  <%= @wagon.type_wagon %>
</p>
<p>
  <strong>Количество верхних мест:</strong>
  <%= @wagon.cnt_top_place %>
</p>
<p>
  <strong>Количество нижних мест:</strong>
  <%= @wagon.cnt_bottom_place %>
</p>

<%= link_to 'Редактировать', edit_wagon_path(@wagon) %> |
<%= link_to 'Назад', wagons_path %>

app/views/welcome/index.html.erb
<h1>Привет, Rails!</h1>

<p>
  <%= link_to 'Список станций', railway_stations_path %>
</p>
<p>
  <%= link_to 'Список маршрутов', routes_path %>
</p>
<p>
  <%= link_to 'Список поездов', trains_path %>
</p>
<p>
  <%= link_to 'Список вагонов', wagons_path %>
</p>
<p>
  <%= link_to 'Список билетов', tickets_path %>
</p>